# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastLaneSubject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FastLaneSubject
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxViewController'
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'FastLaneSubjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FastLaneSubjectUITests' do
    # Pods for testing
  end

end
